# Site settings
author: Bria White
title: Brias Blog
header-img: img/home-bg.png
email: bria.awhite@gmail.com
copyright_name: Bria White
description: > # this means to ignore newlines until "baseurl:"
  SE in the making 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  B-awhite

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
